#!/usr/bin/env python3
import sqlite3

db = sqlite3.connect('/root/diesel_limits/restrictions.db')

# New restrictions gathered from news search (July 2026)
# (region, city, network, client_type, limit_type, limit_value, source_url, source_date)
restrictions = [
    ("Республика Дагестан", None, None, "физлица", "объем",
     "до 20 л бензина / 50 л дизеля",
     "https://tass.ru/obschestvo/27855585", "25.06.2026"),
    ("Ивановская область", None, None, "физлица", "объем",
     "до 30 л бензина / 60 л дизеля",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "02.07.2026"),
    ("Ивановская область", None, None, "физлица", "запрет",
     "запрет продажи в канистры",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "02.07.2026"),
    ("Калининградская область", None, None, "физлица", "объем",
     "до 30 л бензина / 60 л дизеля на авто",
     "https://kaliningrad.rbc.ru/kaliningrad/03/07/2026/6a47747b9a7947ec70cf9c13", "25.06.2026"),
    ("Кемеровская область", None, None, "население", "объем",
     "до 40 л бензина / 80 л дизеля в городе, до 200 л дизеля на трассе",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "23.06.2026"),
    ("Липецкая область", None, None, "физлица", "объем",
     "до 30 л бензина на авто",
     "https://www.lipetsk.kp.ru/daily/277792/5267436/", "24.06.2026"),
    ("Москва", None, "Газпромнефть", "все", "объем",
     "до 30 л бензина / 60 л дизеля, на трассе до 200 л дизеля",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "03.07.2026"),
    ("Москва", None, None, "все", "запрет",
     "запрет продажи в канистры",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "03.07.2026"),
    ("Ростовская область", None, None, "легковые авто", "объем",
     "до 30 л бензина / 60 л дизеля",
     "https://www.rbc.ru/economics/10/07/2026/6a50e9859a7947e50d76ffd8", "10.07.2026"),
    ("Ростовская область", None, None, "грузовики", "объем",
     "до 200 л дизеля",
     "https://www.rbc.ru/economics/10/07/2026/6a50e9859a7947e50d76ffd8", "10.07.2026"),
    ("Ростовская область", None, None, "пассажирский транспорт", "объем",
     "до 300 л дизеля",
     "https://www.rbc.ru/economics/10/07/2026/6a50e9859a7947e50d76ffd8", "10.07.2026"),
    ("Новосибирская область", None, None, "физлица", "объем",
     "до 30 л бензина / 60 л дизеля на машину",
     "https://www.rbc.ru/economics/03/07/2026/6a461d589a79474020d03021", "06.07.2026"),
    ("Воронежская область", "Воронеж", "Лукойл", "физлица", "объем",
     "до 30 л бензина / 60 л дизеля (город), до 60/200 л на трассе",
     "https://finance.mail.ru/article/30-litrov-na-avto-v-kakih-regionah-vveli-ogranicheniya-iz-za-toplivnogo-krizisa-69214349/", "23.06.2026"),
    ("Омская область", None, None, "физлица", "объем",
     "до 40 л бензина / 80 л дизеля в городе, до 200 л дизеля на трассе",
     "https://t.me/HocenkoVP/8377", "23.06.2026"),
    ("Пензенская область", None, None, "физлица", "объем",
     "до 100 л бензина / 200 л дизеля на машину",
     "https://t.me/omelnichenko/10251", "23.06.2026"),
    ("Белгородская область", None, "Лукойл", "физлица", "объем",
     "до 30 л бензина / 60 л дизеля",
     "https://www.kommersant.ru/doc/8797540", "03.07.2026"),
    ("Владимирская область", None, None, "физлица", "объем",
     "до 20-30 л бензина / 40 л дизеля",
     "https://vladtv.ru/society/172950/", "18.06.2026"),
    ("Краснодарский край", None, None, "физлица", "объем",
     "от 20-30 л бензина / 30-60 л дизеля",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "01.07.2026"),
    ("Приморский край", None, None, "большегрузы", "объем",
     "до 100 л дизеля в городе / 200 л на трассе",
     "https://primorsky.ru/news/318665", "29.06.2026"),
    ("Псковская область", None, None, "физлица", "объем",
     "до 40 л дизеля",
     "https://www.mk-pskov.ru/incident/2026/06/15/na-pskovskikh-zapravkakh-pereboi-s-benzinom.html", "15.06.2026"),
    ("Удмуртская Республика", None, None, "физлица", "объем",
     "до 40 л дизеля",
     "https://www.mk-pskov.ru/incident/2026/06/15/na-pskovskikh-zapravkakh-pereboi-s-benzinom.html", "15.06.2026"),
    ("Республика Татарстан", None, "Газпромнефть", "физлица", "объем",
     "до 30 л бензина / 60 л дизеля",
     "https://www.aa.com.tr/ru/ekonomika/geografiya-ogranichenij-na-prodazhu-topliva-v-rossii-prodolzhaet-rasshiryatsya/3983182", "01.07.2026"),
    ("Мурманская область", None, "Лукойл", "физлица", "объем",
     "до 30 л бензина / 60 л дизеля",
     "https://www.aa.com.tr/ru/ekonomika/geografiya-ogranichenij-na-prodazhu-topliva-v-rossii-prodolzhaet-rasshiryatsya/3983182", "01.07.2026"),
    ("Самарская область", None, None, "легковые", "объем",
     "до 40 л бензина / 100 л дизеля",
     "https://www.kommersant.ru/doc/8763813", "24.06.2026"),
    ("Саратовская область", "Саратов", None, "физлица", "объем",
     "до 30 л бензина",
     "https://www.aa.com.tr/ru/ekonomika/geografiya-ogranichenij-na-prodazhu-topliva-v-rossii-prodolzhaet-rasshiryatsya/3983182", "23.06.2026"),
    ("Республика Саха (Якутия)", None, "Саханефтегазсбыт", "физлица", "объем",
     "до 30 л бензина / 200 л дизеля на машину",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "29.06.2026"),
    ("Республика Саха (Якутия)", None, "Саханефтегазсбыт", "физлица", "запрет",
     "запрет продажи в переносные емкости",
     "https://lenta.ru/twz/chto-proiskhodit/prodazha-topliva.htm", "29.06.2026"),
    ("Курганская область", None, None, "физлица", "объем",
     "до 40 л бензина / 80 л дизеля в городе, 200 л дизеля на трассе",
     "https://www.rbc.ru/economics/24/06/2026/6a3b6f359a79470136ec2f16", "24.06.2026"),
    ("Волгоградская область", None, "Лукойл", "физлица", "объем",
     "до 30 л бензина / 60 л дизеля в городе, 200 л дизеля на трассе",
     "https://www.vedomosti.ru/business/articles/2026/06/24/1208285-ob-ogranicheniyah-benzina", "23.06.2026"),
    ("Вологодская область", None, "Лукойл", "физлица", "объем",
     "до 30 л бензина / 60 л дизеля, на трассе до 200 л дизеля",
     "https://t.me/filimonov_official/40341", "23.06.2026"),
    ("Ульяновская область", None, None, "легковые", "объем",
     "до 40 л бензина / 100 л дизеля на авто",
     "https://t-j.ru/news/kakie-regiony-bez-benza/", "25.06.2026"),
    ("Ульяновская область", None, None, "грузовики", "объем",
     "до 300 л дизеля",
     "https://t-j.ru/news/kakie-regiony-bez-benza/", "25.06.2026"),
    ("Забайкальский край", None, None, "физлица", "объем",
     "до 15 л бензина",
     "https://www.aa.com.tr/ru/ekonomika/geografiya-ogranichenij-na-prodazhu-topliva-v-rossii-prodolzhaet-rasshiryatsya/3983182", "01.07.2026"),
    ("Краснодарский край", None, None, "физлица", "объем",
     "до 30 л бензина и 10 л в канистры",
     "https://www.aa.com.tr/ru/ekonomika/geografiya-ogranichenij-na-prodazhu-topliva-v-rossii-prodolzhaet-rasshiryatsya/3983182", "01.07.2026"),
    ("Ленинградская область", None, None, "физлица", "объем",
     "до 100 л бензина на авто",
     "https://finance.mail.ru/article/30-litrov-na-avto-v-kakih-regionah-vveli-ogranicheniya-iz-za-toplivnogo-krizisa-69214349/", "16.06.2026"),
    ("Республика Алтай", None, None, "физлица", "объем",
     "до 30-50 л бензина / 50-100 л дизеля в сутки",
     "https://finance.mail.ru/article/gde-ogranichili-prodazhu-benzina-i-kogda-situaciya-normalizuetsya-69217153/", "09.07.2026"),
    ("Севастополь", None, None, "все", "запрет",
     "продажа только спецслужбам",
     "https://www.vedomosti.ru/business/articles/2026/06/24/1208285-ob-ogranicheniyah-benzina", "21.06.2026"),
    ("Республика Крым", None, None, "все", "запрет",
     "продажа прекращена для физ и юр лиц",
     "https://www.vedomosti.ru/business/articles/2026/06/24/1208285-ob-ogranicheniyah-benzina", "21.06.2026"),
    ("Кировская область", None, "Движение", "физлица", "объем",
     "до 30 л бензина / 100 л дизеля",
     "https://finance.mail.ru/article/gde-ogranichili-prodazhu-benzina-i-kogda-situaciya-normalizuetsya-69217153/", "11.07.2026"),
    ("Пермский край", None, None, "население", "объем",
     "до 40 л бензина / 80 л дизеля в городе, до 200 л дизеля на трассе",
     "https://snob.ru/amp/3117638/", "22.06.2026"),
    ("Томская область", "Стрежевой", None, "все", "объем",
     "до 30-40 л бензина / 80 л дизеля",
     "https://www.kommersant.ru/doc/8763676", "23.06.2026"),
    ("Республика Карелия", None, None, "физлица", "объем",
     "от 20 до 60 л на руки",
     "https://lenta.ru/articles/2026/07/07/prodazha-benzina-ogranicheniya/", "30.06.2026"),
    ("Красноярский край", "Красноярск", "Газпромнефть", "физлица", "объем",
     "до 40 л бензина на машину",
     "https://www.aa.com.tr/ru/ekonomika/geografiya-ogranichenij-na-prodazhu-topliva-v-rossii-prodolzhaet-rasshiryatsya/3983182", "01.07.2026"),
    ("Республика Башкортостан", None, None, "физлица", "объем",
     "до 30 л бензина на авто",
     "https://t-j.ru/news/kakie-regiony-bez-benza/", "27.06.2026"),
    ("Нижегородская область", None, None, "физлица", "объем",
     "до 40 л бензина в одни руки",
     "https://t-j.ru/news/kakie-regiony-bez-benza/", "06.07.2026"),
    # Global measures
    ("Российская Федерация", None, None, "все", "запрет",
     "запрет экспорта дизельного топлива с 8 июля 2026",
     "https://www.vedomosti.ru/business/articles/2026/06/24/1208285-ob-ogranicheniyah-benzina", "08.07.2026"),
    ("Российская Федерация", None, None, "все", "качество",
     "разрешен выпуск бензина и дизеля Евро-3 (сера до 350 мг/кг)",
     "https://lenta.ru/news/2026/07/03/v-rossii-razreshili-vypuskat-benzin-i-dizel-klassa-evro-3-chto-eto-oznachaet-i-bezopasno-li-takoe-toplivo/", "03.07.2026"),
]

inserted = 0
for r in restrictions:
    region, city, network, client, limit_type, limit_value, src, date = r
    try:
        db.execute(
            "INSERT INTO restrictions(region,city,network,client_type,limit_type,limit_value,source_url,source_date,is_current,previous_value) VALUES(?,?,?,?,?,?,?,?,1,?)",
            (region, city, network, client, limit_type, limit_value, src, date, limit_value)
        )
        inserted += 1
    except sqlite3.IntegrityError:
        pass  # already exists

db.commit()
print(f"New restrictions inserted: {inserted}")
print(f"Restrictions total: {db.execute('SELECT COUNT(*) FROM restrictions').fetchone()[0]}")
print(f"Restrictions active: {db.execute('SELECT COUNT(*) FROM restrictions WHERE is_current=1').fetchone()[0]}")
db.close()
